
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tholithemba
 */
public class Patient extends javax.swing.JFrame {

    /**
     * Creates new form Patient
     */
    public Patient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
        
        create_patient();
    }
    
    //inserting data into patint table
    public static void create_patient()
    {
        int patient_id = 1515;
        String name = "Sandile";
        String Surname = "Khendle";
        String date_of_birth = "30-Dec-1983";
        String id_no = "8312304389081";
        String gender = "Male";
        String mob_number = "0667443410";
        String email = "sandile@gmail.com";
        String occupation=" Tax driver";
        
        create_address();
        
        PreparedStatement ps;
        
        String add_data = "INSERT INTO `PATIENT`(`PATIENT_ID`,`NAME`, `SURNAME`, `DOB`, `ID_OR_PASSORT_NUMBER`, `GENDER`,"
                + " `MOBILE_NUMBER`, `EMAIL`, `OCCUPATION`, `ADDRESS_ID`, `MED_CONDITION_ID`) VALUES"
                + " (?,?,?,?,?,?,?,?,?,?,?)";
        try
        {
            ps = Connect2database.getConnection().prepareStatement(add_data);
            
            ps.setInt(1, patient_id);
            ps.setString(2, name);
            ps.setString(3, Surname);
            ps.setString(4, date_of_birth);
            ps.setString(5, id_no);
            ps.setString(6, gender);
            ps.setString(7, mob_number);
            ps.setString(8, email);
            ps.setString(9, occupation);
            ps.setInt(10, 2);
            ps.setInt(11, 10);
            
            if(ps.executeUpdate()>0)
            {
                
                JOptionPane.showMessageDialog(null, "patient detatials was captured successfully");
            }
            
        }catch(SQLException sq)
        {
            sq.getSQLState();
        }
        
    }
    //end of create_patient
    //inserting data to address table
    public static void create_address()
    {
       String line_1 = "74 Main reef";
       String line_2 = "Soweto";
       String line_3 = "Jabulani";
       String city = "Johannesburg";
       String province = "Gauteng";
       int postal_code = 1723;
       
       PreparedStatement ps;
       
       String address = "INSERT INTO `ADDRESS`(`ADDRESS_LINE_1`, `ADDRESS_LINE_2`,"
               + " `ADDRESS_LINE_3`, `CITY`, `PROVINCE`, `POSTAL_CODE`)"
               + " VALUES (?,?,?,?,?,?)";
       
       try
       {
           ps = Connect2database.getConnection().prepareStatement(address);
           
           ps.setString(1, line_1);
           ps.setString(2, line_2);
           ps.setString(3, line_3);
           ps.setString(4, city);
           ps.setString(5, province);
           ps.setInt(6, postal_code);
        
           if(ps.executeUpdate()>0)
           {
               JOptionPane.showMessageDialog(null, "address captured successfully");
           }
           
       }catch(SQLException sq)
       {
           sq.getSQLState();
       }
         
    }
    //end of create_address

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
